### ISSUE TITLE
1.46 version fail on Fargate request - jenkins fargate plugin java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by i-kit** [jenkinsci/amazon-ecs-plugin#303] opened 2022-12-13 22:08 UTC
### Jenkins and plugins versions report

<details>
  <summary>AWS Fargate / Linux</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux & Linux

### Reproduction steps

1. Update version from 1.41 => 1.46
2. try to run ecs fargate task

### Expected Results

ECS task started

### Actual Results

java.lang.IllegalArgumentException

### Anything else?

1.41 works like charm

**Comment by Stericson** [comment] 2022-12-13 22:33
Duplicate of #291 

See this issue for workarounds. Hopeful fix coming before eoy.

**Closed by Stericson** 2022-12-13 22:33 UTC
Labels: bug
