### ISSUE TITLE
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@af4c69d failed java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by venkatd4u** [jenkinsci/amazon-ecs-plugin#299] opened 2022-12-05 15:23 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

After recent jenkins update to latest image to 2.375.1, we are facing issues with jenkins slave node provisioning.

### Expected Results

Slave node with label fargate-agent getting provisioned

### Actual Results

Node provisioining

**Comment by venkatd4u** [comment] 2022-12-05 15:25
Fargate Slave agent not picking up due to below error

Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@af4c69d failed
java.lang.IllegalArgumentException
	at hudson.slaves.NodeProvisioner$PlannedNode.<init>(NodeProvisioner.java:102)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.provision(ECSCloud.java:283)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy.apply(ECSProvisioningStrategy.java:65)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:325)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:94)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by OneBadSanta** [comment] 2022-12-08 22:48
+1 Same issue. Same solution as @venkatd4u

**Comment by elazo89** [comment] 2022-12-09 08:43
+1 I also experienced this issue in 1.46. Version 1.41 works fine. My Jenkins version is 2.375.1.

**Comment by Stericson** [comment] 2022-12-09 22:19
Duplicate of #291 

This seems to be caused by configurations that need updating in 1.46. It seems that there might be more sensible defaults. Something I'll look into. In the meantime, will close this as a duplicate.

**Closed by Stericson** 2022-12-09 22:19 UTC
Labels: bug
