### ISSUE TITLE
Add support for minimum agents

### ISSUE THREAD

**Issue by MikeKroell** [jenkinsci/amazon-ecs-plugin#304] opened 2022-12-16 14:51 UTC
### What feature do you want to see added?

When running the ECS plug-in, an agent EC2 instance is always running, but there are no executors until a job is launched, leaving the instance idle and still having to wait for an executor to launch. We would like to have a Minimum amount of running executors so we can reduce job launch being that there is always one instance running. 

We cannot use Fargate as we need support to build docker containers.

This request should still kill and relaunch an executor once a job has run on it.

**Comment by Stericson** [comment] 2022-12-18 15:43
This is a duplicate of your previous issue #260.

Please consider submitting a PR with your implementation of this feature.

**Closed by Stericson** 2022-12-18 15:44 UTC
Labels: enhancement

**Comment by MikeKroell** [comment] 2022-12-18 17:17
I would love to, but unfortunately I can’t program in Groovy.
